import { useState } from "react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import {
  DownloadIcon,
  AlertTriangleIcon,
  CheckCircleIcon,
  ShieldIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  Loader2Icon,
} from "lucide-react";
import ComponentSecurityTab from "@/aksec/components/component-security-tab";
import { KubernetesSecurityAnalysis } from "@/aksec/data/kubernetes-security-analysis";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface SecurityRisk {
  category: string;
  severity: "Critical" | "High" | "Medium" | "Low";
  mitigation: string;
}

export interface SecurityRecommendation {
  title: string;
  description: string;
  priority: "high" | "medium" | "low";
}

interface SecurityReportProps {
  report: KubernetesSecurityAnalysis;
}

export default function SecurityReport({
  report,
}: SecurityReportProps) {
  const [activeTab, setActiveTab] = useState("summary");
  const [showAllComponents, setShowAllComponents] = useState(false);
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);

  // PDF Generation function - Comprehensive 5-7 page report
  const generatePDF = async () => {
    setIsGeneratingPDF(true);
    
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 14;
      let yPos = 20;
      
      // Helper function to add page header
      const addPageHeader = (title: string) => {
        doc.setFillColor(41, 128, 185);
        doc.rect(0, 0, pageWidth, 12, 'F');
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(255, 255, 255);
        doc.text(title, margin, 8);
        doc.text(`Page ${doc.getNumberOfPages()}`, pageWidth - margin, 8, { align: "right" });
        doc.setTextColor(0, 0, 0);
        return 20;
      };
      
      // Helper function to add page footer
      const addPageFooter = () => {
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(128, 128, 128);
        doc.text("Generated by Info Security Analyzer", margin, pageHeight - 10);
        doc.text(new Date().toLocaleString(), pageWidth - margin, pageHeight - 10, { align: "right" });
        doc.setTextColor(0, 0, 0);
      };
      
      // Helper to check and add new page if needed
      const checkNewPage = (requiredSpace: number, sectionTitle?: string) => {
        if (yPos + requiredSpace > pageHeight - 25) {
          addPageFooter();
          doc.addPage();
          yPos = sectionTitle ? addPageHeader(sectionTitle) : 20;
          return true;
        }
        return false;
      };

      // Calculate statistics
      const totalComponents = report.components?.length || 0;
      const totalDataFlows = report.dataFlows?.length || 0;
      const allRisks = (report.components || []).flatMap(c => c.securityRisks || []);
      const totalRisksCount = allRisks.length;
      const criticalCount = allRisks.filter(r => r.severity === "Critical").length;
      const highCount = allRisks.filter(r => r.severity === "High").length;
      const mediumCount = allRisks.filter(r => r.severity === "Medium").length;
      const lowCount = allRisks.filter(r => r.severity === "Low").length;
      
      // Determine overall risk level
      const riskLevel = criticalCount > 0 ? "CRITICAL" : highCount > 0 ? "HIGH" : mediumCount > 0 ? "MEDIUM" : "LOW";
      const riskColor = criticalCount > 0 ? [220, 53, 69] : highCount > 0 ? [255, 107, 107] : mediumCount > 0 ? [255, 193, 7] : [40, 167, 69];
      
      // ============== PAGE 1: COVER PAGE ==============
      // Background gradient effect
      doc.setFillColor(41, 128, 185);
      doc.rect(0, 0, pageWidth, 80, 'F');
      
      // Title
      doc.setFontSize(28);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(255, 255, 255);
      doc.text("Security Analysis Report", pageWidth / 2, 35, { align: "center" });
      
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.text("STRIDE Threat Analysis & Risk Assessment", pageWidth / 2, 48, { align: "center" });
      
      doc.setFontSize(10);
      doc.text(`Generated on ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`, pageWidth / 2, 62, { align: "center" });
      
      // Risk Level Badge
      doc.setTextColor(0, 0, 0);
      yPos = 100;
      
      doc.setFillColor(riskColor[0], riskColor[1], riskColor[2]);
      doc.roundedRect(pageWidth / 2 - 40, yPos - 8, 80, 20, 3, 3, 'F');
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(255, 255, 255);
      doc.text(`${riskLevel} RISK`, pageWidth / 2, yPos + 5, { align: "center" });
      doc.setTextColor(0, 0, 0);
      
      // Key Statistics Box
      yPos = 140;
      doc.setFillColor(248, 249, 250);
      doc.roundedRect(margin, yPos - 5, pageWidth - 2 * margin, 50, 3, 3, 'F');
      doc.setDrawColor(200, 200, 200);
      doc.roundedRect(margin, yPos - 5, pageWidth - 2 * margin, 50, 3, 3, 'S');
      
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Assessment Overview", margin + 5, yPos + 5);
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      const statsY = yPos + 20;
      const colWidth = (pageWidth - 2 * margin) / 4;
      
      // Stats columns
      const stats = [
        { label: "Components", value: totalComponents.toString() },
        { label: "Data Flows", value: totalDataFlows.toString() },
        { label: "Total Risks", value: totalRisksCount.toString() },
        { label: "Critical/High", value: `${criticalCount + highCount}` }
      ];
      
      stats.forEach((stat, i) => {
        const x = margin + 5 + (i * colWidth);
        doc.setFontSize(18);
        doc.setFont("helvetica", "bold");
        doc.text(stat.value, x + colWidth / 2 - 5, statsY);
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100, 100, 100);
        doc.text(stat.label, x + colWidth / 2 - 5, statsY + 12);
        doc.setTextColor(0, 0, 0);
      });
      
      // Risk Breakdown
      yPos = 210;
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Risk Severity Breakdown", margin, yPos);
      yPos += 15;
      
      const riskBreakdown = [
        { label: "Critical", count: criticalCount, color: [220, 53, 69] },
        { label: "High", count: highCount, color: [255, 107, 107] },
        { label: "Medium", count: mediumCount, color: [255, 193, 7] },
        { label: "Low", count: lowCount, color: [40, 167, 69] }
      ];
      
      riskBreakdown.forEach((risk, i) => {
        const barWidth = totalRisksCount > 0 ? (risk.count / totalRisksCount) * 120 : 0;
        doc.setFillColor(risk.color[0], risk.color[1], risk.color[2]);
        doc.rect(margin + 60, yPos + (i * 12), barWidth, 8, 'F');
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.text(risk.label, margin, yPos + (i * 12) + 6);
        doc.text(risk.count.toString(), margin + 185, yPos + (i * 12) + 6);
      });
      
      addPageFooter();
      
      // ============== PAGE 2: EXECUTIVE SUMMARY ==============
      doc.addPage();
      yPos = addPageHeader("Executive Summary");
      
      // Summary Text
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Security Posture Assessment", margin, yPos);
      yPos += 8;
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      
      // Generate summary text
      let summaryText = "";
      if (criticalCount > 0 || highCount > 0) {
        const topComponents = (report.assessmentSummary?.topRisks || []).slice(0, 3).map(r => r.component).join(', ');
        summaryText = `This architecture has ${criticalCount > 0 ? `${criticalCount} critical` : ''}${criticalCount > 0 && highCount > 0 ? ' and ' : ''}${highCount > 0 ? `${highCount} high-risk` : ''} vulnerabilities that require immediate attention. Focus on securing ${topComponents || 'key components'}. Implementing the recommended security controls will significantly improve the overall security posture.`;
      } else if (mediumCount > 0) {
        summaryText = `This architecture has ${mediumCount} medium-risk vulnerabilities. While not critical, addressing these will strengthen the security posture.`;
      } else {
        summaryText = "This architecture has a good security posture with only minor risks identified. Continue to monitor and maintain security best practices.";
      }
      
      const splitSummary = doc.splitTextToSize(summaryText, pageWidth - 2 * margin);
      doc.text(splitSummary, margin, yPos);
      yPos += splitSummary.length * 5 + 15;
      
      // Detected Components Section
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Detected Components", margin, yPos);
      yPos += 8;
      
      const componentsByType: { [key: string]: string[] } = {};
      (report.components || []).forEach(c => {
        const type = c.type || "Unknown";
        if (!componentsByType[type]) componentsByType[type] = [];
        componentsByType[type].push(c.name);
      });
      
      Object.entries(componentsByType).forEach(([type, components]) => {
        checkNewPage(15, "Executive Summary");
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.text(`${type}:`, margin, yPos);
        doc.setFont("helvetica", "normal");
        doc.text(components.join(', '), margin + 50, yPos);
        yPos += 8;
      });
      
      yPos += 10;
      
      // Component Risk Summary Table
      checkNewPage(60, "Executive Summary");
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Component Risk Summary", margin, yPos);
      yPos += 5;
      
      const componentSummaryData = (report.components || [])
        .map(comp => {
          const risks = comp.securityRisks || [];
          return {
            name: comp.name || "N/A",
            type: comp.type || "N/A",
            total: risks.length,
            critical: risks.filter(r => r.severity === "Critical").length,
            high: risks.filter(r => r.severity === "High").length
          };
        })
        .sort((a, b) => (b.critical + b.high) - (a.critical + a.high));
      
      autoTable(doc, {
        startY: yPos,
        head: [["Component", "Type", "Total Risks", "Critical", "High"]],
        body: componentSummaryData.map(c => [c.name, c.type, c.total.toString(), c.critical.toString(), c.high.toString()]),
        theme: "striped",
        headStyles: { fillColor: [41, 128, 185], fontSize: 9 },
        styles: { fontSize: 8, cellPadding: 3 },
        margin: { left: margin, right: margin },
        tableWidth: 'auto',
      });
      
      // @ts-ignore
      yPos = doc.lastAutoTable.finalY + 10;
      addPageFooter();
      
      // ============== PAGE 3: TOP SECURITY RISKS ==============
      doc.addPage();
      yPos = addPageHeader("Top Security Risks");
      
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Priority Risks Requiring Immediate Attention", margin, yPos);
      yPos += 10;
      
      const topRisks = report.assessmentSummary?.topRisks || [];
      
      if (topRisks.length > 0) {
        topRisks.forEach((risk, index) => {
          checkNewPage(45, "Top Security Risks");
          
          // Risk card
          doc.setFillColor(255, 248, 248);
          doc.setDrawColor(220, 53, 69);
          doc.roundedRect(margin, yPos, pageWidth - 2 * margin, 35, 2, 2, 'FD');
          
          // Risk number badge
          doc.setFillColor(220, 53, 69);
          doc.circle(margin + 10, yPos + 10, 6, 'F');
          doc.setFontSize(10);
          doc.setFont("helvetica", "bold");
          doc.setTextColor(255, 255, 255);
          doc.text((index + 1).toString(), margin + 10, yPos + 12, { align: "center" });
          doc.setTextColor(0, 0, 0);
          
          // Component name and impact
          doc.setFontSize(10);
          doc.setFont("helvetica", "bold");
          doc.text(risk.component || "Unknown", margin + 22, yPos + 8);
          
          doc.setFillColor(255, 107, 107);
          doc.roundedRect(margin + 22 + doc.getTextWidth(risk.component || "Unknown") + 5, yPos + 3, 25, 8, 2, 2, 'F');
          doc.setFontSize(7);
          doc.setTextColor(255, 255, 255);
          doc.text(risk.impact || "High", margin + 22 + doc.getTextWidth(risk.component || "Unknown") + 17.5, yPos + 8, { align: "center" });
          doc.setTextColor(0, 0, 0);
          
          // Risk description
          doc.setFontSize(9);
          doc.setFont("helvetica", "normal");
          doc.text(`Risk: ${risk.risk || "N/A"}`, margin + 22, yPos + 18);
          
          // Recommendation
          doc.setFont("helvetica", "italic");
          const recText = doc.splitTextToSize(`Recommendation: ${risk.recommendation || "N/A"}`, pageWidth - 2 * margin - 25);
          doc.text(recText, margin + 22, yPos + 26);
          
          yPos += 42;
        });
      } else {
        doc.setFontSize(10);
        doc.setFont("helvetica", "italic");
        doc.text("No critical risks identified.", margin, yPos);
        yPos += 15;
      }
      
      addPageFooter();
      
      // ============== PAGE 4: DATA FLOW ANALYSIS ==============
      doc.addPage();
      yPos = addPageHeader("Data Flow Analysis");
      
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Communication Paths & Associated Risks", margin, yPos);
      yPos += 10;
      
      const dataFlows = report.dataFlows || [];
      
      if (dataFlows.length > 0) {
        dataFlows.forEach((flow, index) => {
          checkNewPage(50, "Data Flow Analysis");
          
          // Flow header
          doc.setFillColor(240, 248, 255);
          doc.setDrawColor(41, 128, 185);
          doc.roundedRect(margin, yPos, pageWidth - 2 * margin, 12, 2, 2, 'FD');
          
          doc.setFontSize(10);
          doc.setFont("helvetica", "bold");
          doc.text(`${flow.source || "Unknown"} → ${flow.target || "Unknown"}`, margin + 5, yPos + 8);
          yPos += 15;
          
          // Description
          doc.setFontSize(9);
          doc.setFont("helvetica", "normal");
          doc.text(`Description: ${flow.description || "N/A"}`, margin + 5, yPos);
          yPos += 8;
          
          // Flow risks
          const flowRisks = flow.securityRisks || [];
          if (flowRisks.length > 0) {
          autoTable(doc, {
            startY: yPos,
            head: [["Risk", "Impact", "Mitigation"]],
            body: flowRisks.map(r => [
              r.risk || "N/A",
              r.impact || "N/A",
              r.mitigation || "N/A"
            ]),
            theme: "grid",
            headStyles: { fillColor: [52, 73, 94], fontSize: 8 },
            styles: { fontSize: 7, cellPadding: 2, overflow: 'linebreak' },
            margin: { left: margin + 5, right: margin },
            tableWidth: 'auto',
          });
            // @ts-ignore
            yPos = doc.lastAutoTable.finalY + 10;
          } else {
            yPos += 5;
          }
        });
      } else {
        doc.setFontSize(10);
        doc.setFont("helvetica", "italic");
        doc.text("No data flows identified.", margin, yPos);
      }
      
      addPageFooter();
      
      // ============== PAGE 5-6: DETAILED COMPONENT ANALYSIS ==============
      doc.addPage();
      yPos = addPageHeader("Detailed Component Analysis");
      
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("STRIDE Analysis by Component", margin, yPos);
      yPos += 10;
      
      (report.components || []).forEach((component) => {
        checkNewPage(60, "Detailed Component Analysis");
        
        // Component header
        doc.setFillColor(41, 128, 185);
        doc.roundedRect(margin, yPos, pageWidth - 2 * margin, 18, 2, 2, 'F');
        
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(255, 255, 255);
        doc.text(component.name || "Unknown Component", margin + 5, yPos + 7);
        
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.text(`Type: ${component.type || "Unknown"}`, margin + 5, yPos + 14);
        doc.setTextColor(0, 0, 0);
        yPos += 22;
        
        // Component description
        if (component.description) {
          doc.setFontSize(9);
          doc.setFont("helvetica", "italic");
          const descText = doc.splitTextToSize(component.description, pageWidth - 2 * margin - 10);
          doc.text(descText, margin + 5, yPos);
          yPos += descText.length * 4 + 5;
        }
        
        // Relationships
        if (component.relationships && component.relationships.length > 0) {
          doc.setFontSize(8);
          doc.setFont("helvetica", "bold");
          doc.text("Related Components:", margin + 5, yPos);
          doc.setFont("helvetica", "normal");
          doc.text(component.relationships.join(', '), margin + 45, yPos);
          yPos += 8;
        }
        
        // Security risks table
        const compRisks = component.securityRisks || [];
        if (compRisks.length > 0) {
          checkNewPage(40, "Detailed Component Analysis");
          
          autoTable(doc, {
            startY: yPos,
            head: [["STRIDE Category", "Severity", "Mitigation"]],
            body: compRisks.map(risk => [
              risk.category || "N/A",
              risk.severity || "N/A",
              risk.mitigation || "N/A"
            ]),
            theme: "striped",
            headStyles: { 
              fillColor: [52, 73, 94], 
              fontSize: 8,
              fontStyle: 'bold'
            },
            styles: { fontSize: 8, cellPadding: 3, overflow: 'linebreak' },
            margin: { left: margin, right: margin },
            tableWidth: 'auto',
            didParseCell: (data) => {
              // Color code severity
              if (data.column.index === 1 && data.section === 'body') {
                const severity = data.cell.raw as string;
                if (severity === 'Critical') {
                  data.cell.styles.textColor = [220, 53, 69];
                  data.cell.styles.fontStyle = 'bold';
                } else if (severity === 'High') {
                  data.cell.styles.textColor = [255, 107, 107];
                  data.cell.styles.fontStyle = 'bold';
                } else if (severity === 'Medium') {
                  data.cell.styles.textColor = [255, 193, 7];
                } else {
                  data.cell.styles.textColor = [40, 167, 69];
                }
              }
            },
          });
          // @ts-ignore
          yPos = doc.lastAutoTable.finalY + 15;
        } else {
          doc.setFontSize(9);
          doc.setFont("helvetica", "italic");
          doc.setTextColor(100, 100, 100);
          doc.text("No security risks identified for this component.", margin + 5, yPos);
          doc.setTextColor(0, 0, 0);
          yPos += 15;
        }
      });
      
      addPageFooter();
      
      // ============== PAGE 7: RECOMMENDATIONS & NEXT STEPS ==============
      doc.addPage();
      yPos = addPageHeader("Recommendations & Next Steps");
      
      // Actionable Recommendations
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Actionable Recommendations", margin, yPos);
      yPos += 10;
      
      const nextSteps = report.assessmentSummary?.nextSteps || [];
      
      if (nextSteps.length > 0) {
        nextSteps.forEach((step, index) => {
          checkNewPage(20, "Recommendations & Next Steps");
          
          // Recommendation box
          doc.setFillColor(240, 255, 240);
          doc.setDrawColor(40, 167, 69);
          doc.roundedRect(margin, yPos, pageWidth - 2 * margin, 15, 2, 2, 'FD');
          
          // Number badge
          doc.setFillColor(40, 167, 69);
          doc.circle(margin + 10, yPos + 7.5, 5, 'F');
          doc.setFontSize(9);
          doc.setFont("helvetica", "bold");
          doc.setTextColor(255, 255, 255);
          doc.text((index + 1).toString(), margin + 10, yPos + 9, { align: "center" });
          doc.setTextColor(0, 0, 0);
          
          // Step text
          doc.setFontSize(9);
          doc.setFont("helvetica", "normal");
          const stepText = doc.splitTextToSize(step, pageWidth - 2 * margin - 30);
          doc.text(stepText, margin + 20, yPos + 6 + (stepText.length > 1 ? 0 : 3));
          
          yPos += 20;
        });
      }
      
      yPos += 15;
      checkNewPage(60, "Recommendations & Next Steps");
      
      // Security Posture Summary Box
      doc.setFillColor(232, 244, 253);
      doc.setDrawColor(41, 128, 185);
      doc.roundedRect(margin, yPos, pageWidth - 2 * margin, 45, 3, 3, 'FD');
      
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Security Posture Summary", margin + 10, yPos + 12);
      
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      
      const postureSummary = criticalCount > 0 
        ? "This architecture requires immediate security attention. Critical vulnerabilities have been identified that could lead to significant security breaches. Prioritize addressing the top risks listed in this report."
        : highCount > 0
        ? "This architecture has notable security concerns that should be addressed promptly. While no critical issues were found, the high-risk vulnerabilities identified could pose significant threats if exploited."
        : "This architecture demonstrates a reasonable security posture. Continue to monitor and implement the recommended improvements to maintain and enhance security."
      
      const summaryLines = doc.splitTextToSize(postureSummary, pageWidth - 2 * margin - 20);
      doc.text(summaryLines, margin + 10, yPos + 22);
      
      yPos += 55;
      
      // Report metadata
      checkNewPage(30, "Recommendations & Next Steps");
      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128);
      doc.text("Report Information", margin, yPos);
      yPos += 8;
      doc.text(`Analysis Method: STRIDE Threat Modeling Framework`, margin, yPos);
      yPos += 5;
      doc.text(`Components Analyzed: ${totalComponents}`, margin, yPos);
      yPos += 5;
      doc.text(`Data Flows Analyzed: ${totalDataFlows}`, margin, yPos);
      yPos += 5;
      doc.text(`Total Security Risks Identified: ${totalRisksCount}`, margin, yPos);
      doc.setTextColor(0, 0, 0);
      
      addPageFooter();
      
      // Save the PDF
      doc.save(`security-analysis-report-${new Date().toISOString().split('T')[0]}.pdf`);
      
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  // Calculate total risks across all components (all severities)
  const totalRisks = report.components.reduce(
    (acc, component) => acc + component.securityRisks.length,
    0
  );

  // Count risks by severity
  const criticalRisks = report.components.reduce(
    (count, component) =>
      count +
      component.securityRisks.filter((risk) => risk.severity === "Critical")
        .length,
    0
  );

  const highRisks = report.components.reduce(
    (count, component) =>
      count +
      component.securityRisks.filter((risk) => risk.severity === "High").length,
    0
  );

  const mediumRisks = report.components.reduce(
    (count, component) =>
      count +
      component.securityRisks.filter((risk) => risk.severity === "Medium")
        .length,
    0
  );

  const lowRisks = report.components.reduce(
    (count, component) =>
      count +
      component.securityRisks.filter((risk) => risk.severity === "Low").length,
    0
  );

  const overallSeverity =
    criticalRisks > 0
      ? "critical"
      : highRisks > 0
        ? "high"
        : mediumRisks > 0
          ? "medium"
          : "low";

  const getSeverityBadge = (severity: string) => {
    switch (severity) {
      case "critical":
        return (
          <Badge variant="destructive" className="ml-2">
            Critical Risk
          </Badge>
        );

      case "high":
        return (
          <Badge
            variant="outline"
            className="ml-2 bg-red-100 text-red-800 dark:bg-red-900/20 dark:text-red-400 border-red-200 dark:border-red-800/30"
          >
            High Risk
          </Badge>
        );

      case "medium":
        return (
          <Badge
            variant="outline"
            className="ml-2 bg-amber-100 text-amber-800 dark:bg-amber-900/20 dark:text-amber-400 border-amber-200 dark:border-amber-800/30"
          >
            Medium Risk
          </Badge>
        );

      case "low":
        return (
          <Badge
            variant="outline"
            className="ml-2 bg-green-100 text-green-800 dark:bg-green-900/20 dark:text-green-400 border-green-200 dark:border-green-800/30"
          >
            Low Risk
          </Badge>
        );

      default:
        return (
          <Badge
            variant="outline"
            className="ml-2 bg-green-100 text-green-800 dark:bg-green-900/20 dark:text-green-400 border-green-200 dark:border-green-800/30"
          >
            No Risk
          </Badge>
        );
    }
  };

  // Get components to display based on expand state
  const componentsToShow = showAllComponents 
    ? report.components 
    : report.components.slice(0, 5);
  const hasMoreComponents = report.components.length > 5;

  return (
    <div className="w-full space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold">Security Analysis Report</h2>
          <p className="text-muted-foreground">
            Generated on {new Date().toLocaleString()}
          </p>
        </div>
        <div className="flex items-center space-x-2">
          <Button size="sm" onClick={generatePDF} disabled={isGeneratingPDF}>
            {isGeneratingPDF ? (
              <>
                <Loader2Icon className="h-4 w-4 mr-2 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <DownloadIcon className="h-4 w-4 mr-2" />
                Download PDF
              </>
            )}
          </Button>
        </div>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center">
            Executive Summary
            {getSeverityBadge(overallSeverity)}
          </CardTitle>
          <CardDescription>
            Overall security assessment of your architecture
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex flex-col md:flex-row gap-6">
            <div className="flex-1">
              <p className="text-sm leading-relaxed">
                {criticalRisks > 0 || highRisks > 0 ? (
                  <>
                    This architecture has {criticalRisks > 0 ? `${criticalRisks} critical` : ''} 
                    {criticalRisks > 0 && highRisks > 0 ? ' and ' : ''}
                    {highRisks > 0 ? `${highRisks} high-risk` : ''} vulnerabilities 
                    that require immediate attention. Focus on securing{' '}
                    {report.assessmentSummary.topRisks.slice(0, 3).map(r => r.component).join(', ')}.
                Implementing the recommended security controls will
                significantly improve the overall security posture.
                  </>
                ) : mediumRisks > 0 ? (
                  <>
                    This architecture has {mediumRisks} medium-risk vulnerabilities.
                    While not critical, addressing these will strengthen the security posture.
                    Focus on the recommendations provided for{' '}
                    {report.components.slice(0, 3).map(c => c.name).join(', ')}.
                  </>
                ) : (
                  <>
                    This architecture has a good security posture with only minor risks identified.
                    Continue to monitor and maintain security best practices across all components.
                  </>
                )}
              </p>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-6">
                <Card>
                  <CardHeader className="py-2">
                    <CardTitle className="text-sm font-medium text-muted-foreground">
                      Total Risks
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold">{totalRisks}</div>
                    <div className="text-xs text-muted-foreground mt-1">
                      {criticalRisks + highRisks} Critical/High
                    </div>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader className="py-2">
                    <CardTitle className="text-sm font-medium text-muted-foreground">
                      Components
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold">
                      {report.components.length}
                    </div>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader className="py-2">
                    <CardTitle className="text-sm font-medium text-muted-foreground">
                      Data Flows
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold">
                      {report.dataFlows.length}
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>

            <div className="md:w-64 space-y-4">
              {/* Only show Critical and High severity counts prominently */}
              <div className="flex items-center justify-between">
                <div className="flex items-center">
                  <AlertTriangleIcon className="h-4 w-4 text-red-500 mr-2" />
                  <span className="text-sm">Critical Severity</span>
                </div>
                <Badge
                  variant="outline"
                  className="bg-red-50 text-red-600 dark:bg-red-900/20 dark:text-red-400"
                >
                  {criticalRisks}
                </Badge>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center">
                  <AlertTriangleIcon className="h-4 w-4 text-orange-500 mr-2" />
                  <span className="text-sm">High Severity</span>
                </div>
                <Badge
                  variant="outline"
                  className="bg-orange-50 text-orange-600 dark:bg-orange-900/20 dark:text-orange-400"
                >
                  {highRisks}
                </Badge>
              </div>

              {/* Show Medium/Low in a more subtle way */}
              {(mediumRisks > 0 || lowRisks > 0) && (
                <div className="text-xs text-muted-foreground pt-1">
                  Also: {mediumRisks > 0 && `${mediumRisks} Medium`}{mediumRisks > 0 && lowRisks > 0 && ', '}{lowRisks > 0 && `${lowRisks} Low`}
                </div>
              )}

              <Separator />

              <div>
                <div className="flex items-center justify-between mb-2">
                  <h4 className="text-sm font-medium">
                    Detected Components ({report.components.length})
                </h4>
                  {hasMoreComponents && (
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-6 px-2 text-xs"
                      onClick={() => setShowAllComponents(!showAllComponents)}
                    >
                      {showAllComponents ? (
                        <>
                          <ChevronUpIcon className="h-3 w-3 mr-1" />
                          Show Less
                        </>
                      ) : (
                        <>
                          <ChevronDownIcon className="h-3 w-3 mr-1" />
                          Show All
                        </>
                      )}
                    </Button>
                  )}
                </div>
                <div className="flex flex-wrap gap-1">
                  {componentsToShow.map((component, index) => (
                    <Badge key={index} variant="secondary" className="text-xs">
                      {component.name}
                    </Badge>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="summary">STRIDE Analysis</TabsTrigger>
          <TabsTrigger value="component-security">
            <ShieldIcon className="h-4 w-4 mr-2" />
            Component Security
          </TabsTrigger>
        </TabsList>
        <TabsContent value="summary" className="space-y-4 mt-6">
          <Card>
            <CardHeader>
              <CardTitle className="text-xl">
                Actionable Recommendations
              </CardTitle>
              <CardDescription>
                Prioritized security improvements for your architecture
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                {report.assessmentSummary.nextSteps.map((step, index) => (
                  <div
                    key={index}
                    className="p-4 border rounded-md border-green-200 bg-green-50 dark:border-green-800/30 dark:bg-green-900/10"
                  >
                    <div className="flex items-start">
                      <div className="p-2 rounded-full mr-4 bg-green-100 dark:bg-green-900/20">
                        <CheckCircleIcon className="h-5 w-5 text-green-600 dark:text-green-400" />
                      </div>
                      <div className="flex-1">
                        <p className="mt-2 text-sm">{step}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="component-security" className="mt-6">
          <ComponentSecurityTab analysisData={report} />
        </TabsContent>
      </Tabs>
    </div>
  );
}
